### Import the data via CSV files

In [252]:
import pandas as pd

# Replace 'your_file.csv' with the path to your CSV file
nfl_current = pd.read_csv('23_season.csv')
nfl_history = pd.read_csv('nfltil22.csv')

In [253]:
team_abb = ['crd', 'atl', 'rav', 'buf','car', 'chi',
            'cin', 'cle', 'dal', 'det', 'gnb', 'htx', 'clt', 'jax', 'kan', 'sdg',
            'ram', 'rai', 'mia', 'nwe', 'nor', 'nyg', 'nyj', 'phi', 'pit', 'sea', 'sfo', 'tam', 'oti', 'was']

In [254]:
pd.set_option('display.max_columns', None)

In [255]:
nfl_current.head()

,Season,Week,Team,Day,Date,Unnamed: 3,Unnamed: 4,OT,Unnamed: 6,Opp,Tm,Opp.1,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Y/A,NY/A,Cmp%,Rate,Att.1,Yds.2,Y/A.1,TD.1,FGM,FGA,XPM,XPA,Pnt,Yds.3,3DConv,3DAtt,4DConv,4DAtt,ToP,Week.1,Day.1,Date.1,Unnamed: 3.1,Unnamed: 4.1,OT.1,Unnamed: 6.1,Opp.2,Tm.1,Opp.1.1,Cmp.1,Att.2,Yds.4,TD.2,Int.1,Sk.1,Yds.1.1,Y/A.2,NY/A.1,Cmp%.1,Rate.1,Att.1.1,Yds.2.1,Y/A.1.1,TD.1.1,FGM.1,FGA.1,XPM.1,XPA.1,Pnt.1,Yds.3.1,3DConv.1,3DAtt.1,4DConv.1,4DAtt.1,ToP.1
0,2023,1,CRD,Sun,September 10,boxscore,L,NaN,@,Washington Commanders,16.0,20.0,21.0,30.0,114.0,0.0,0.0,3.0,18.0,4.4,3.5,70.0,76.2,25.0,96.0,3.8,0.0,3.0,3.0,1.0,1.0,5.0,235.0,4.0,14.0,0.0,1.0,28:36,1,Sun,September 10,boxscore,L,NaN,@,Washington Commanders,16.0,20.0,21.0,30.0,114.0,0.0,0.0,3.0,18.0,4.4,3.5,70.0,76.2,25.0,96.0,3.8,0.0,3.0,3.0,1.0,1.0,5.0,235.0,4.0,14.0,0.0,1.0,28:36
1,2023,2,CRD,Sun,September 17,boxscore,L,NaN,NaN,New York Giants,28.0,31.0,21.0,31.0,228.0,1.0,0.0,0.0,0.0,7.4,7.4,67.7,99.9,29.0,151.0,5.2,2.0,2.0,3.0,2.0,2.0,3.0,146.0,4.0,10.0,0.0,0.0,30:37,2,Sun,September 17,boxscore,L,NaN,NaN,New York Giants,28.0,31.0,21.0,31.0,228.0,1.0,0.0,0.0,0.0,7.4,7.4,67.7,99.9,29.0,151.0,5.2,2.0,2.0,3.0,2.0,2.0,3.0,146.0,4.0,10.0,0.0,0.0,30:37
2,2023,3,CRD,Sun,September 24,boxscore,W,NaN,NaN,Dallas Cowboys,28.0,16.0,17.0,21.0,178.0,1.0,0.0,2.0,11.0,9.0,7.7,81.0,117.9,30.0,222.0,7.4,2.0,3.0,3.0,1.0,1.0,2.0,94.0,5.0,10.0,0.0,0.0,25:27,3,Sun,September 24,boxscore,W,NaN,NaN,Dallas Cowboys,28.0,16.0,17.0,21.0,178.0,1.0,0.0,2.0,11.0,9.0,7.7,81.0,117.9,30.0,222.0,7.4,2.0,3.0,3.0,1.0,1.0,2.0,94.0,5.0,10.0,0.0,0.0,25:27
3,2023,4,CRD,Sun,October 1,boxscore,L,NaN,@,San Francisco 49ers,16.0,35.0,28.0,41.0,257.0,2.0,0.0,1.0,8.0,6.5,6.1,68.3,101.4,25.0,105.0,4.2,0.0,1.0,1.0,1.0,1.0,3.0,117.0,8.0,15.0,2.0,3.0,30:46,4,Sun,October 1,boxscore,L,NaN,@,San Francisco 49ers,16.0,35.0,28.0,41.0,257.0,2.0,0.0,1.0,8.0,6.5,6.1,68.3,101.4,25.0,105.0,4.2,0.0,1.0,1.0,1.0,1.0,3.0,117.0,8.0,15.0,2.0,3.0,30:46
4,2023,5,CRD,Sun,October 8,boxscore,L,NaN,NaN,Cincinnati Bengals,20.0,34.0,15.0,32.0,152.0,2.0,2.0,3.0,14.0,5.2,4.3,46.9,55.7,22.0,142.0,6.5,1.0,0.0,0.0,2.0,3.0,4.0,219.0,4.0,11.0,0.0,3.0,21:50,5,Sun,October 8,boxscore,L,NaN,NaN,Cincinnati Bengals,20.0,34.0,15.0,32.0,152.0,2.0,2.0,3.0,14.0,5.2,4.3,46.9,55.7,22.0,142.0,6.5,1.0,0.0,0.0,2.0,3.0,4.0,219.0,4.0,11.0,0.0,3.0,21:50

In [256]:
#print the column names in nfl_history
nfl_history.columns

Index(['Season', 'Week', 'Team', 'Day', 'Date', 'Unnamed: 3', 'Unnamed: 4',
       'OT', 'Unnamed: 6', 'Opp', 'Tm', 'Opp.1', 'Cmp', 'Att', 'Yds', 'TD',
       'Int', 'Sk', 'Yds.1', 'Y/A', 'NY/A', 'Cmp%', 'Rate', 'Att.1', 'Yds.2',
       'Y/A.1', 'TD.1', 'FGM', 'FGA', 'XPM', 'XPA', 'Pnt', 'Yds.3', '3DConv',
       '3DAtt', '4DConv', '4DAtt', 'ToP', 'Week.1', 'Day.1', 'Date.1',
       'Unnamed: 3.1', 'Unnamed: 4.1', 'OT.1', 'Unnamed: 6.1', 'Opp.2', 'Tm.1',
       'Opp.1.1', 'Cmp.1', 'Att.2', 'Yds.4', 'TD.2', 'Int.1', 'Sk.1',
       'Yds.1.1', 'Y/A.2', 'NY/A.1', 'Cmp%.1', 'Rate.1', 'Att.1.1', 'Yds.2.1',
       'Y/A.1.1', 'TD.1.1', 'FGM.1', 'FGA.1', 'XPM.1', 'XPA.1', 'Pnt.1',
       'Yds.3.1', '3DConv.1', '3DAtt.1', '4DConv.1', '4DAtt.1', 'ToP.1'],
      dtype='object')

### Need to assign names to unnamed columns
    - Drop Unnamed 3
    - Unnamed4 and Unnamed: 4.1= W/L
    - OT is true or false
    - Unnamed 6 and Unnamed: 6.1 is home or away
    - Drop Week.1, Day.1, Date.1, Unnamed: 3.1

In [257]:
#rename the columns in nfl_history
nfl_history.rename(columns={'Unnamed: 4': 'WL', 'Unnamed: 4.1': 'WL.1', 'Unnamed: 6' : 'HoA', 'Unnamed: 6.1' : 'HoA.1', 'Tm': 'TeamPts', 'Tm.1': 'TeamPts.1','Opp.1' : 'OppPts', 'Opp.2' : 'OppPts2'}, inplace=True)
nfl_history.drop(columns=['Unnamed: 3', 'Unnamed: 3.1'], inplace=True)
nfl_current.rename(columns={'Unnamed: 4': 'WL', 'Unnamed: 4.1': 'WL.1', 'Unnamed: 6' : 'HoA', 'Unnamed: 6.1' : 'HoA.1', 'Tm': 'TeamPts', 'Tm.1': 'TeamPts.1','Opp.1' : 'OppPts', 'Opp.2' : 'OppPts2'}, inplace=True)
nfl_current.drop(columns=['Unnamed: 3', 'Unnamed: 3.1'], inplace=True)

In [258]:
if nfl_current.columns.all() == nfl_history.columns.all():
    print('Columns are the same')
print(nfl_current.columns)

Columns are the same
Index(['Season', 'Week', 'Team', 'Day', 'Date', 'WL', 'OT', 'HoA', 'Opp',
       'TeamPts', 'OppPts', 'Cmp', 'Att', 'Yds', 'TD', 'Int', 'Sk', 'Yds.1',
       'Y/A', 'NY/A', 'Cmp%', 'Rate', 'Att.1', 'Yds.2', 'Y/A.1', 'TD.1', 'FGM',
       'FGA', 'XPM', 'XPA', 'Pnt', 'Yds.3', '3DConv', '3DAtt', '4DConv',
       '4DAtt', 'ToP', 'Week.1', 'Day.1', 'Date.1', 'WL.1', 'OT.1', 'HoA.1',
       'OppPts2', 'TeamPts.1', 'Opp.1.1', 'Cmp.1', 'Att.2', 'Yds.4', 'TD.2',
       'Int.1', 'Sk.1', 'Yds.1.1', 'Y/A.2', 'NY/A.1', 'Cmp%.1', 'Rate.1',
       'Att.1.1', 'Yds.2.1', 'Y/A.1.1', 'TD.1.1', 'FGM.1', 'FGA.1', 'XPM.1',
       'XPA.1', 'Pnt.1', 'Yds.3.1', '3DConv.1', '3DAtt.1', '4DConv.1',
       '4DAtt.1', 'ToP.1'],
      dtype='object')

### Duplicate these dataframes

In [259]:
nflpast = nfl_history.copy()
nflnow = nfl_current.copy()

In [260]:
#Sort the dataframes by team and date
nflpast.sort_values(by=['Team','Date'], inplace=True)
nflnow.sort_values(by=['Team','Date'], inplace=True)

In [261]:
nflpast_whole = nflpast.copy()
nflnow_whole = nflnow.copy()

In [262]:
#Create a new dataframe of the average of every 15 games for all columns containing numbers
nflpastavg = nflpast.groupby('Team').rolling(5, min_periods=1).mean().reset_index()
nflpastavg.drop(columns=['level_1'], inplace=True)
nflpastavg.dropna(inplace=True)
nflpastavg.reset_index(inplace=True)
nflpastavg.drop(columns=['index'], inplace=True)

C:\Users\Joey\AppData\Local\Temp\ipykernel_18300\1407034806.py:2: FutureWarning: Dropping of nuisance columns in rolling operations is deprecated; in a future version this will raise TypeError. Select only valid columns before calling the operation. Dropped columns were Index(['Date', 'Date.1', 'Day', 'Day.1', 'HoA', 'HoA.1', 'OT', 'OT.1', 'Opp',
       'OppPts2', 'ToP', 'ToP.1', 'WL', 'WL.1'],
      dtype='object')
  nflpastavg = nflpast.groupby('Team').rolling(5, min_periods=1).mean().reset_index()

In [263]:
nflpastavg.head()

,Team,Season,Week,TeamPts,OppPts,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Y/A,NY/A,Cmp%,Rate,Att.1,Yds.2,Y/A.1,TD.1,FGM,FGA,XPM,XPA,Pnt,Yds.3,3DConv,3DAtt,4DConv,4DAtt,Week.1,TeamPts.1,Opp.1.1,Cmp.1,Att.2,Yds.4,TD.2,Int.1,Sk.1,Yds.1.1,Y/A.2,NY/A.1,Cmp%.1,Rate.1,Att.1.1,Yds.2.1,Y/A.1.1,TD.1.1,FGM.1,FGA.1,XPM.1,XPA.1,Pnt.1,Yds.3.1,3DConv.1,3DAtt.1,4DConv.1,4DAtt.1
0,ATL,2013.000000,13.000000,34.000000,31.000000,28.000000,47.000000,272.000000,1.000000,0.00,6.000000,39.000000,6.600000,5.100,59.600000,82.900000,30.000000,151.0,5.000000,3.000000,2.0,2.000000,4.000000,4.000000,7.0,278.000000,10.000000,18.00,0.0,0.0,13.000000,34.000000,31.000000,28.000000,47.000000,272.000000,1.000000,0.00,6.000000,39.000000,6.600000,5.100,59.600000,82.900000,30.000000,151.0,5.000000,3.000000,2.0,2.000000,4.000000,4.000000,7.0,278.000000,10.000000,18.00,0.0,0.0
1,ATL,2012.000000,13.500000,32.500000,27.000000,25.000000,42.500000,290.000000,2.500000,0.00,4.500000,25.500000,7.500000,6.300,58.750000,101.050000,29.000000,118.5,4.050000,1.500000,1.5,2.000000,4.000000,4.000000,6.5,282.500000,9.000000,17.50,0.0,0.0,13.500000,32.500000,27.000000,25.000000,42.500000,290.000000,2.500000,0.00,4.500000,25.500000,7.500000,6.300,58.750000,101.050000,29.000000,118.5,4.050000,1.500000,1.5,2.000000,4.000000,4.000000,6.5,282.500000,9.000000,17.50,0.0,0.0
2,ATL,2013.333333,13.666667,35.666667,22.666667,22.666667,38.333333,266.666667,2.666667,0.00,3.666667,22.666667,7.633333,6.500,59.166667,106.033333,27.666667,101.0,3.566667,1.333333,1.0,1.333333,4.666667,4.666667,7.0,326.666667,7.333333,16.00,0.0,0.0,13.666667,35.666667,22.666667,22.666667,38.333333,266.666667,2.666667,0.00,3.666667,22.666667,7.633333,6.500,59.166667,106.033333,27.666667,101.0,3.566667,1.333333,1.0,1.333333,4.666667,4.666667,7.0,326.666667,7.333333,16.00,0.0,0.0
3,ATL,2012.500000,13.750000,34.500000,19.500000,22.000000,37.250000,250.000000,2.250000,0.25,3.500000,23.750000,7.400000,6.225,59.075000,97.825000,29.750000,107.5,3.550000,1.750000,1.0,1.250000,4.500000,4.500000,7.0,315.750000,7.750000,16.25,0.0,0.0,13.750000,34.500000,19.500000,22.000000,37.250000,250.000000,2.250000,0.25,3.500000,23.750000,7.400000,6.225,59.075000,97.825000,29.750000,107.5,3.550000,1.750000,1.0,1.250000,4.500000,4.500000,7.0,315.750000,7.750000,16.25,0.0,0.0
4,ATL,2014.200000,13.800000,33.400000,19.800000,21.400000,35.400000,238.000000,2.000000,0.20,2.800000,19.000000,7.280000,6.340,60.840000,98.020000,31.000000,111.6,3.560000,1.600000,1.4,1.600000,4.000000,4.000000,6.0,274.600000,7.600000,15.80,0.4,0.4,13.800000,33.400000,19.800000,21.400000,35.400000,238.000000,2.000000,0.20,2.800000,19.000000,7.280000,6.340,60.840000,98.020000,31.000000,111.6,3.560000,1.600000,1.4,1.600000,4.000000,4.000000,6.0,274.600000,7.600000,15.80,0.4,0.4

In [264]:
nflpastavg.drop(columns=['Season','Week'], inplace=True)

In [265]:
nflpastavg.head()

,Team,TeamPts,OppPts,Cmp,Att,Yds,TD,Int,Sk,Yds.1,Y/A,NY/A,Cmp%,Rate,Att.1,Yds.2,Y/A.1,TD.1,FGM,FGA,XPM,XPA,Pnt,Yds.3,3DConv,3DAtt,4DConv,4DAtt,Week.1,TeamPts.1,Opp.1.1,Cmp.1,Att.2,Yds.4,TD.2,Int.1,Sk.1,Yds.1.1,Y/A.2,NY/A.1,Cmp%.1,Rate.1,Att.1.1,Yds.2.1,Y/A.1.1,TD.1.1,FGM.1,FGA.1,XPM.1,XPA.1,Pnt.1,Yds.3.1,3DConv.1,3DAtt.1,4DConv.1,4DAtt.1
0,ATL,34.000000,31.000000,28.000000,47.000000,272.000000,1.000000,0.00,6.000000,39.000000,6.600000,5.100,59.600000,82.900000,30.000000,151.0,5.000000,3.000000,2.0,2.000000,4.000000,4.000000,7.0,278.000000,10.000000,18.00,0.0,0.0,13.000000,34.000000,31.000000,28.000000,47.000000,272.000000,1.000000,0.00,6.000000,39.000000,6.600000,5.100,59.600000,82.900000,30.000000,151.0,5.000000,3.000000,2.0,2.000000,4.000000,4.000000,7.0,278.000000,10.000000,18.00,0.0,0.0
1,ATL,32.500000,27.000000,25.000000,42.500000,290.000000,2.500000,0.00,4.500000,25.500000,7.500000,6.300,58.750000,101.050000,29.000000,118.5,4.050000,1.500000,1.5,2.000000,4.000000,4.000000,6.5,282.500000,9.000000,17.50,0.0,0.0,13.500000,32.500000,27.000000,25.000000,42.500000,290.000000,2.500000,0.00,4.500000,25.500000,7.500000,6.300,58.750000,101.050000,29.000000,118.5,4.050000,1.500000,1.5,2.000000,4.000000,4.000000,6.5,282.500000,9.000000,17.50,0.0,0.0
2,ATL,35.666667,22.666667,22.666667,38.333333,266.666667,2.666667,0.00,3.666667,22.666667,7.633333,6.500,59.166667,106.033333,27.666667,101.0,3.566667,1.333333,1.0,1.333333,4.666667,4.666667,7.0,326.666667,7.333333,16.00,0.0,0.0,13.666667,35.666667,22.666667,22.666667,38.333333,266.666667,2.666667,0.00,3.666667,22.666667,7.633333,6.500,59.166667,106.033333,27.666667,101.0,3.566667,1.333333,1.0,1.333333,4.666667,4.666667,7.0,326.666667,7.333333,16.00,0.0,0.0
3,ATL,34.500000,19.500000,22.000000,37.250000,250.000000,2.250000,0.25,3.500000,23.750000,7.400000,6.225,59.075000,97.825000,29.750000,107.5,3.550000,1.750000,1.0,1.250000,4.500000,4.500000,7.0,315.750000,7.750000,16.25,0.0,0.0,13.750000,34.500000,19.500000,22.000000,37.250000,250.000000,2.250000,0.25,3.500000,23.750000,7.400000,6.225,59.075000,97.825000,29.750000,107.5,3.550000,1.750000,1.0,1.250000,4.500000,4.500000,7.0,315.750000,7.750000,16.25,0.0,0.0
4,ATL,33.400000,19.800000,21.400000,35.400000,238.000000,2.000000,0.20,2.800000,19.000000,7.280000,6.340,60.840000,98.020000,31.000000,111.6,3.560000,1.600000,1.4,1.600000,4.000000,4.000000,6.0,274.600000,7.600000,15.80,0.4,0.4,13.800000,33.400000,19.800000,21.400000,35.400000,238.000000,2.000000,0.20,2.800000,19.000000,7.280000,6.340,60.840000,98.020000,31.000000,111.6,3.560000,1.600000,1.4,1.600000,4.000000,4.000000,6.0,274.600000,7.600000,15.80,0.4,0.4

In [266]:
nflpast = nflpast[nflpast.columns.intersection(nflpastavg.columns)]
if nflpast.columns.all() == nflpastavg.columns.all():
    print('Columns are the same')

Columns are the same

In [267]:
print(nflpast['Team'].dtype)

object

In [268]:
nflpast['Team'] = nflpast['Team'].astype(str)
nflpast['Team'] = nflpast['Team'].str.lower()
nflpastavg['Team'] = nflpastavg['Team'].str.lower()

# Convert the 'team_abb' list to lowercase
team_abb_lower = [team.lower() for team in team_abb]

# Define a mapping from lowercase team abbreviations to indices
team_mapping = {team_abb_lower: idx for idx, team_abb_lower in enumerate(team_abb_lower)}

# Update the 'Team' column in 'nflpast' using the mapping
nflpast['Team'] = nflpast['Team'].map(team_mapping)

# Update the 'Team' column in 'nflpastavg' using the mapping
nflpastavg['Team'] = nflpastavg['Team'].map(team_mapping)

In [269]:
nflpast.shape

(6298, 56)

### Attempting to use a MLP

In [270]:
import torch
import torch.nn as nn
import numpy as np
import scipy.io 
import random
import math
import matplotlib.pyplot as plt
import torch.nn.functional as F
import os
import seaborn as sn
import pandas as pd
os.environ['KMP_DUPLICATE_LIB_OK']='True' 

from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score

In [271]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        self.layer1 = nn.Linear(54, 64)
        self.bn1 = nn.BatchNorm1d(64)
        
        self.layer2 = nn.Linear(64, 56)
        self.bn2 = nn.BatchNorm1d(56)
        
        self.layer3 = nn.Linear(56, 48)
        self.bn3 = nn.BatchNorm1d(48)
        
        self.layer4 = nn.Linear(48, 40)
        self.bn4 = nn.BatchNorm1d(40)
        
        self.layer5 = nn.Linear(40, 36)
        self.bn5 = nn.BatchNorm1d(36)
        
        self.layer6 = nn.Linear(36, 32)
        self.bn6 = nn.BatchNorm1d(32)
        
        self.layer7 = nn.Linear(32, 28)
        self.bn7 = nn.BatchNorm1d(28)
        
        self.layer8 = nn.Linear(28, 24)
        self.bn8 = nn.BatchNorm1d(24)
        
        self.layer9 = nn.Linear(24, 20)
        self.bn9 = nn.BatchNorm1d(20)
        
        self.layer10 = nn.Linear(20, 16)
        self.bn10 = nn.BatchNorm1d(16)
        
        self.layer11 = nn.Linear(16, 12)
        self.bn11 = nn.BatchNorm1d(12)
        
        self.layer12 = nn.Linear(12, 8)
        self.bn12 = nn.BatchNorm1d(8)
        
        self.layer13 = nn.Linear(8, 4)
        self.bn13 = nn.BatchNorm1d(4)
        
        self.layer14 = nn.Linear(4, 2)

    def forward(self, x):
        x = F.relu(self.bn1(self.layer1(x)))
        x = F.relu(self.bn2(self.layer2(x)))
        x = F.relu(self.bn3(self.layer3(x)))
        x = F.relu(self.bn4(self.layer4(x)))
        x = F.relu(self.bn5(self.layer5(x)))
        x = F.relu(self.bn6(self.layer6(x)))
        x = F.relu(self.bn7(self.layer7(x)))
        x = F.relu(self.bn8(self.layer8(x)))
        x = F.relu(self.bn9(self.layer9(x)))
        x = F.relu(self.bn10(self.layer10(x)))
        x = F.relu(self.bn11(self.layer11(x)))
        x = F.relu(self.bn12(self.layer12(x)))
        x = F.relu(self.bn13(self.layer13(x)))
        x = self.layer14(x)
        return x

net = Net()

In [272]:
from sklearn.model_selection import train_test_split
X = nflpast.drop(['TeamPts', 'OppPts'], axis=1)  # Features
y = nflpast[['TeamPts', 'OppPts']]  # Labels

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [273]:
#Normalize the data except for column 'Team'
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_numpy = X_train.values
X_test_numpy = X_test.values
X_train_numpy[:,1:] = scaler.fit_transform(X_train_numpy[:,1:])
X_test_numpy[:,1:] = scaler.transform(X_test_numpy[:,1:])
X_train = torch.tensor(X_train_numpy, dtype=torch.float32)
X_test = torch.tensor(X_test_numpy, dtype=torch.float32)
y_train = y_train.values
y_test = y_test.values

In [274]:

X_train  = torch.tensor(np.array(X_train), dtype=torch.float32)
X_test = torch.tensor(np.array(X_test), dtype=torch.float32)
y_train = torch.tensor(np.array(y_train), dtype=torch.float32)
y_test = torch.tensor(np.array(y_test), dtype=torch.float32)
print(X_train)

tensor([[ 1.0000, -0.3045, -0.5634,  ..., -0.8244,  1.9001,  0.8364],
        [10.0000, -0.9670,  0.0226,  ...,  1.5148, -0.6843, -0.9356],
        [21.0000,  1.0204,  0.4913,  ...,  1.1250, -0.6843, -0.9356],
        ...,
        [18.0000, -0.4701, -0.6806,  ..., -0.0447,  0.6079,  0.8364],
        [ 4.0000, -1.9607, -0.7978,  ...,  0.3452, -0.6843, -0.9356],
        [21.0000,  2.6766,  3.3039,  ...,  3.4642,  0.6079,  0.8364]])

In [275]:
#define a loss function and optimizer
from torch.optim.lr_scheduler import StepLR
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(net.parameters(), lr=0.05)
scheduler = StepLR(optimizer, step_size=3, gamma=0.85)
num_epochs = 300  # Define the number of training epochs
for epoch in range(num_epochs):
    optimizer.zero_grad()  # Zero the gradients
    outputs = net(X_train)  # Forward pass
    loss = criterion(outputs, y_train)  # Calculate the loss
    loss.backward()  # Backpropagation
    optimizer.step()  # Update the model parameters
    scheduler.step()
    # Print the loss at each epoch
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item()}')

Epoch [1/300], Loss: 612.0591430664062
Epoch [2/300], Loss: 527.3550415039062
Epoch [3/300], Loss: 384.7447509765625
Epoch [4/300], Loss: 159.92234802246094

Epoch [5/300], Loss: 163.21572875976562
Epoch [6/300], Loss: 107.17957305908203
Epoch [7/300], Loss: 113.4748306274414
Epoch [8/300], Loss: 118.45337677001953
Epoch [9/300], Loss: 99.64213562011719
Epoch [10/300], Loss: 95.69099426269531
Epoch [11/300], Loss: 80.7226333618164
Epoch [12/300], Loss: 75.89661407470703
Epoch [13/300], Loss: 74.42252349853516
Epoch [14/300], Loss: 79.45407104492188
Epoch [15/300], Loss: 81.93042755126953
Epoch [16/300], Loss: 74.63004302978516
Epoch [17/300], Loss: 69.60136413574219
Epoch [18/300], Loss: 65.9425277709961
Epoch [19/300], Loss: 64.0547866821289
Epoch [20/300], Loss: 62.90264129638672
Epoch [21/300], Loss: 63.59018325805664
Epoch [22/300], Loss: 67.397705078125
Epoch [23/300], Loss: 64.40653228759766
Epoch [24/300], Loss: 60.69027328491211
Epoch [25/300], Loss: 59.47600173950195
Epoch [26/300], Loss: 58.53597640991211
Epoch [27/300], Loss: 57.97384262084961
Epoch [28/300], Loss: 57.51707077026367
Epoch [29/300], Loss: 57.275146484375
Epoch [30/300], Loss: 57.0357666015625
Epoch [31/300], Loss: 57.116756439208984
Epoch [32/300], Loss: 56.661746978759766
Epoch [33/300], Loss: 56.2895622253418
Epoch [34/300], Loss: 56.085731506347656
Epoch [35/300], Loss: 55.70137023925781
Epoch [36/300], Loss: 55.40987777709961
Epoch [37/300], Loss: 55.2353630065918
Epoch [38/300], Loss: 55.080223083496094
Epoch [39/300], Loss: 54.96387481689453
Epoch [40/300], Loss: 54.85633087158203
Epoch [41/300], Loss: 54.7651481628418
Epoch [42/300], Loss: 54.68610382080078
Epoch [43/300], Loss: 54.605220794677734
Epoch [44/300], Loss: 54.534549713134766
Epoch [45/300], Loss: 54.46513366699219
Epoch [46/300], Loss: 54.39576721191406
Epoch [47/300], Loss: 54.33686447143555
Epoch [48/300], Loss: 54.2797737121582
Epoch [49/300], Loss: 54.222347259521484
Epoch [50/300], Loss: 54.172210693359375
Epoch [51/300], Loss: 54.121978759765625
Epoch [52/300], Loss: 54.07159423828125
Epoch [53/300], Loss: 54.027645111083984
Epoch [54/300], Loss: 53.983154296875
Epoch [55/300], Loss: 53.93820571899414
Epoch [56/300], Loss: 53.899295806884766
Epoch [57/300], Loss: 53.85960388183594
Epoch [58/300], Loss: 53.81904220581055
Epoch [59/300], Loss: 53.78277587890625
Epoch [60/300], Loss: 53.74616622924805
Epoch [61/300], Loss: 53.708675384521484
Epoch [62/300], Loss: 53.6757698059082
Epoch [63/300], Loss: 53.64207077026367
Epoch [64/300], Loss: 53.607688903808594
Epoch [65/300], Loss: 53.578330993652344
Epoch [66/300], Loss: 53.548160552978516
Epoch [67/300], Loss: 53.51786422729492
Epoch [68/300], Loss: 53.49174880981445
Epoch [69/300], Loss: 53.46533966064453
Epoch [70/300], Loss: 53.438255310058594
Epoch [71/300], Loss: 53.414920806884766
Epoch [72/300], Loss: 53.39086151123047
Epoch [73/300], Loss: 53.3664665222168
Epoch [74/300], Loss: 53.345611572265625
Epoch [75/300], Loss: 53.32361602783203
Epoch [76/300], Loss: 53.30070877075195
Epoch [77/300], Loss: 53.281288146972656
Epoch [78/300], Loss: 53.261810302734375
Epoch [79/300], Loss: 53.24217987060547
Epoch [80/300], Loss: 53.22528839111328
Epoch [81/300], Loss: 53.20823669433594
Epoch [82/300], Loss: 53.19142532348633
Epoch [83/300], Loss: 53.17718505859375
Epoch [84/300], Loss: 53.1628303527832
Epoch [85/300], Loss: 53.14804458618164
Epoch [86/300], Loss: 53.13535690307617
Epoch [87/300], Loss: 53.122859954833984
Epoch [88/300], Loss: 53.1101188659668
Epoch [89/300], Loss: 53.0988655090332
Epoch [90/300], Loss: 53.087520599365234
Epoch [91/300], Loss: 53.0760612487793
Epoch [92/300], Loss: 53.06630325317383
Epoch [93/300], Loss: 53.056793212890625
Epoch [94/300], Loss: 53.04738998413086
Epoch [95/300], Loss: 53.03932571411133
Epoch [96/300], Loss: 53.0312385559082
Epoch [97/300], Loss: 53.02321243286133
Epoch [98/300], Loss: 53.0163688659668
Epoch [99/300], Loss: 53.009544372558594
Epoch [100/300], Loss: 53.002723693847656
Epoch [101/300], Loss: 52.99686050415039
Epoch [102/300], Loss: 52.99101638793945
Epoch [103/300], Loss: 52.98525619506836
Epoch [104/300], Loss: 52.980384826660156
Epoch [105/300], Loss: 52.97542953491211
Epoch [106/300], Loss: 52.97038269042969
Epoch [107/300], Loss: 52.96605682373047
Epoch [108/300], Loss: 52.96171569824219
Epoch [109/300], Loss: 52.95737838745117
Epoch [110/300], Loss: 52.95368957519531
Epoch [111/300], Loss: 52.95000457763672
Epoch [112/300], Loss: 52.94633865356445
Epoch [113/300], Loss: 52.94322967529297
Epoch [114/300], Loss: 52.94012451171875
Epoch [115/300], Loss: 52.93697738647461
Epoch [116/300], Loss: 52.93423843383789
Epoch [117/300], Loss: 52.931514739990234
Epoch [118/300], Loss: 52.92881774902344
Epoch [119/300], Loss: 52.92652130126953
Epoch [120/300], Loss: 52.92422103881836
Epoch [121/300], Loss: 52.92191696166992
Epoch [122/300], Loss: 52.919952392578125
Epoch [123/300], Loss: 52.917972564697266
Epoch [124/300], Loss: 52.91599655151367
Epoch [125/300], Loss: 52.91431427001953
Epoch [126/300], Loss: 52.912628173828125
Epoch [127/300], Loss: 52.91093826293945
Epoch [128/300], Loss: 52.90951156616211
Epoch [129/300], Loss: 52.908084869384766
Epoch [130/300], Loss: 52.906654357910156
Epoch [131/300], Loss: 52.905418395996094
Epoch [132/300], Loss: 52.904197692871094
Epoch [133/300], Loss: 52.902992248535156
Epoch [134/300], Loss: 52.90196228027344
Epoch [135/300], Loss: 52.90092849731445
Epoch [136/300], Loss: 52.899906158447266
Epoch [137/300], Loss: 52.8990364074707
Epoch [138/300], Loss: 52.898162841796875
Epoch [139/300], Loss: 52.89728546142578
Epoch [140/300], Loss: 52.896541595458984
Epoch [141/300], Loss: 52.89579772949219
Epoch [142/300], Loss: 52.89505386352539
Epoch [143/300], Loss: 52.8944206237793
Epoch [144/300], Loss: 52.893795013427734
Epoch [145/300], Loss: 52.89316177368164
Epoch [146/300], Loss: 52.892635345458984
Epoch [147/300], Loss: 52.8921012878418
Epoch [148/300], Loss: 52.89156723022461
Epoch [149/300], Loss: 52.89111328125
Epoch [150/300], Loss: 52.890663146972656
Epoch [151/300], Loss: 52.890201568603516
Epoch [152/300], Loss: 52.88982009887695
Epoch [153/300], Loss: 52.88943862915039
Epoch [154/300], Loss: 52.8890495300293
Epoch [155/300], Loss: 52.88872528076172
Epoch [156/300], Loss: 52.888397216796875
Epoch [157/300], Loss: 52.88806915283203
Epoch [158/300], Loss: 52.88779067993164
Epoch [159/300], Loss: 52.88751220703125
Epoch [160/300], Loss: 52.88723373413086
Epoch [161/300], Loss: 52.88699722290039
Epoch [162/300], Loss: 52.88675308227539
Epoch [163/300], Loss: 52.886512756347656
Epoch [164/300], Loss: 52.886314392089844
Epoch [165/300], Loss: 52.88611602783203
Epoch [166/300], Loss: 52.88591766357422
Epoch [167/300], Loss: 52.8857421875
Epoch [168/300], Loss: 52.88557052612305
Epoch [169/300], Loss: 52.88539505004883
Epoch [170/300], Loss: 52.88524627685547
Epoch [171/300], Loss: 52.88510513305664
Epoch [172/300], Loss: 52.88495635986328
Epoch [173/300], Loss: 52.884830474853516
Epoch [174/300], Loss: 52.88471221923828
Epoch [175/300], Loss: 52.88459014892578
Epoch [176/300], Loss: 52.88447952270508
Epoch [177/300], Loss: 52.88438034057617
Epoch [178/300], Loss: 52.8842658996582
Epoch [179/300], Loss: 52.88418197631836
Epoch [180/300], Loss: 52.88408660888672
Epoch [181/300], Loss: 52.883995056152344
Epoch [182/300], Loss: 52.88392639160156
Epoch [183/300], Loss: 52.883846282958984
Epoch [184/300], Loss: 52.88376998901367
Epoch [185/300], Loss: 52.88370132446289
Epoch [186/300], Loss: 52.88364791870117
Epoch [187/300], Loss: 52.88357162475586
Epoch [188/300], Loss: 52.88352966308594
Epoch [189/300], Loss: 52.88346862792969
Epoch [190/300], Loss: 52.8834114074707
Epoch [191/300], Loss: 52.88336944580078
Epoch [192/300], Loss: 52.883323669433594
Epoch [193/300], Loss: 52.88327407836914
Epoch [194/300], Loss: 52.88323211669922
Epoch [195/300], Loss: 52.88319396972656
Epoch [196/300], Loss: 52.883155822753906
Epoch [197/300], Loss: 52.88312530517578
Epoch [198/300], Loss: 52.883087158203125
Epoch [199/300], Loss: 52.883056640625
Epoch [200/300], Loss: 52.883026123046875
Epoch [201/300], Loss: 52.88299560546875
Epoch [202/300], Loss: 52.882965087890625
Epoch [203/300], Loss: 52.8829460144043
Epoch [204/300], Loss: 52.88291549682617
Epoch [205/300], Loss: 52.882896423339844
Epoch [206/300], Loss: 52.882877349853516
Epoch [207/300], Loss: 52.88285446166992
Epoch [208/300], Loss: 52.882835388183594
Epoch [209/300], Loss: 52.882816314697266
Epoch [210/300], Loss: 52.88280487060547
Epoch [211/300], Loss: 52.88277816772461
Epoch [212/300], Loss: 52.88277053833008
Epoch [213/300], Loss: 52.882755279541016
Epoch [214/300], Loss: 52.88273620605469
Epoch [215/300], Loss: 52.882720947265625
Epoch [216/300], Loss: 52.88270950317383
Epoch [217/300], Loss: 52.8826904296875
Epoch [218/300], Loss: 52.88269805908203
Epoch [219/300], Loss: 52.8826789855957
Epoch [220/300], Loss: 52.882667541503906
Epoch [221/300], Loss: 52.88265609741211
Epoch [222/300], Loss: 52.88264846801758
Epoch [223/300], Loss: 52.88264083862305
Epoch [224/300], Loss: 52.88262939453125
Epoch [225/300], Loss: 52.88262176513672
Epoch [226/300], Loss: 52.88262176513672
Epoch [227/300], Loss: 52.88261795043945
Epoch [228/300], Loss: 52.882606506347656
Epoch [229/300], Loss: 52.882598876953125
Epoch [230/300], Loss: 52.882591247558594
Epoch [231/300], Loss: 52.88258743286133
Epoch [232/300], Loss: 52.8825798034668
Epoch [233/300], Loss: 52.8825798034668
Epoch [234/300], Loss: 52.8825798034668
Epoch [235/300], Loss: 52.882572174072266
Epoch [236/300], Loss: 52.882568359375
Epoch [237/300], Loss: 52.88256072998047
Epoch [238/300], Loss: 52.88256072998047
Epoch [239/300], Loss: 52.8825569152832
Epoch [240/300], Loss: 52.8825569152832
Epoch [241/300], Loss: 52.8825569152832
Epoch [242/300], Loss: 52.88254928588867
Epoch [243/300], Loss: 52.88254928588867
Epoch [244/300], Loss: 52.88254928588867
Epoch [245/300], Loss: 52.88254165649414
Epoch [246/300], Loss: 52.88254165649414
Epoch [247/300], Loss: 52.882537841796875
Epoch [248/300], Loss: 52.882537841796875
Epoch [249/300], Loss: 52.882537841796875
Epoch [250/300], Loss: 52.882537841796875
Epoch [251/300], Loss: 52.882530212402344
Epoch [252/300], Loss: 52.882530212402344
Epoch [253/300], Loss: 52.882530212402344
Epoch [254/300], Loss: 52.882530212402344
Epoch [255/300], Loss: 52.882530212402344
Epoch [256/300], Loss: 52.882530212402344
Epoch [257/300], Loss: 52.88252258300781
Epoch [258/300], Loss: 52.88252258300781
Epoch [259/300], Loss: 52.88252258300781
Epoch [260/300], Loss: 52.88252258300781
Epoch [261/300], Loss: 52.88252258300781
Epoch [262/300], Loss: 52.88252258300781
Epoch [263/300], Loss: 52.88252258300781
Epoch [264/300], Loss: 52.88252258300781
Epoch [265/300], Loss: 52.88252258300781
Epoch [266/300], Loss: 52.88252258300781
Epoch [267/300], Loss: 52.88252258300781
Epoch [268/300], Loss: 52.88251876831055
Epoch [269/300], Loss: 52.88251876831055
Epoch [270/300], Loss: 52.88252258300781
Epoch [271/300], Loss: 52.88251876831055
Epoch [272/300], Loss: 52.88251876831055
Epoch [273/300], Loss: 52.88251876831055
Epoch [274/300], Loss: 52.88251876831055
Epoch [275/300], Loss: 52.88251876831055
Epoch [276/300], Loss: 52.88251876831055
Epoch [277/300], Loss: 52.88251876831055
Epoch [278/300], Loss: 52.88251876831055
Epoch [279/300], Loss: 52.88251876831055
Epoch [280/300], Loss: 52.88251876831055
Epoch [281/300], Loss: 52.88251876831055
Epoch [282/300], Loss: 52.88251876831055
Epoch [283/300], Loss: 52.88251876831055
Epoch [284/300], Loss: 52.88251876831055
Epoch [285/300], Loss: 52.88251876831055
Epoch [286/300], Loss: 52.88251876831055
Epoch [287/300], Loss: 52.88251876831055
Epoch [288/300], Loss: 52.88251876831055
Epoch [289/300], Loss: 52.88251876831055
Epoch [290/300], Loss: 52.88251876831055
Epoch [291/300], Loss: 52.88251876831055
Epoch [292/300], Loss: 52.88251876831055
Epoch [293/300], Loss: 52.88251876831055
Epoch [294/300], Loss: 52.88251876831055
Epoch [295/300], Loss: 52.88251876831055
Epoch [296/300], Loss: 52.88251876831055
Epoch [297/300], Loss: 52.88251876831055
Epoch [298/300], Loss: 52.88251876831055
Epoch [299/300], Loss: 52.88251876831055
Epoch [300/300], Loss: 52.88251876831055

In [276]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
net.eval()
with torch.no_grad():
    train_predictions = net(X_train)
    test_predictions = net(X_test)
print("Training Predictions:", train_predictions)
print("Training R-squared:", r2_score(y_train, train_predictions))
print("Validation R-squared:", r2_score(y_test, test_predictions))
print("Training MSE:", mean_squared_error(y_train, train_predictions))
print("Validation MSE:", mean_squared_error(y_test, test_predictions))
print("Training MAE:", mean_absolute_error(y_train, train_predictions))
print("Validation MAE:", mean_absolute_error(y_test, test_predictions))

Training Predictions: tensor([[42.0492, 30.5366],
        [22.3765, 24.4517],
        [39.5344, 29.2136],
        ...,
        [15.4436, 18.1667],
        [17.2878, 19.8355],
        [20.4160, 22.6335]])
Training R-squared: 0.4851120878739858
Validation R-squared: 0.4793432507883006
Training MSE: 52.885216
Validation MSE: 53.350517
Training MAE: 5.5599327
Validation MAE: 5.624342

In [277]:
#save the model to a file and save
torch.save(net.state_dict(), 'nfl_model.pt')

AttributeError: module 'torch' has no attribute '_utils'

In [ ]:
import pandas as pd

# Assuming your dataframe is named 'nflpastavg'
# Assuming you have already defined 'team_abb'

# Prompt user for the first team
team1 = input("Enter the first team abbreviation: ").lower()

# Get the last entry for the first team
team1_data = nflpastavg[nflpastavg['Team'] == team_abb.index(team1)].iloc[-1, :28]

# Prompt user for the second team
team2 = input("Enter the second team abbreviation: ").lower()

# Get the last entry for the second team
team2_data = nflpastavg[nflpastavg['Team'] == team_abb.index(team2)].iloc[-1, :28]

# Concatenate the data
concatenated_data = pd.concat([team1_data, team2_data])

# Display the concatenated data
print(concatenated_data)

Team         0.00
TeamPts     19.00
OppPts      22.20
Cmp         23.80
Att         40.20
Yds        245.60
TD           1.40
Int          0.80
Sk           2.80
Yds.1       15.80
Y/A          6.52
NY/A         5.76
Cmp%        59.60
Rate        80.24
Att.1       22.00
Yds.2       83.60
Y/A.1        3.82
TD.1         0.40
FGM          1.80
FGA          2.00
XPM          1.20
XPA          1.20
Pnt          5.40
Yds.3      257.20
3DConv       5.20
3DAtt       13.40
4DConv       0.00
4DAtt        0.20
Team         1.00
TeamPts     23.60
OppPts      25.40
Cmp         26.60
Att         40.20
Yds        302.60
TD           2.00
Int          0.80
Sk           2.60
Yds.1       18.60
Y/A          8.08
NY/A         7.24
Cmp%        66.52
Rate        99.16
Att.1       19.40
Yds.2       88.40
Y/A.1        4.66
TD.1         0.60
FGM          2.00
FGA          2.00
XPM          2.00
XPA          2.20
Pnt          4.00
Yds.3      181.20
3DConv       4.00
3DAtt       11.00
4DConv       0.40
4DAtt        0.80
dtype: float64

In [ ]:

# Extract values from the DataFrame and convert to a PyTorch tensor
tensor_data = torch.tensor(concatenated_data.values, dtype=torch.float32)

# Now, tensor_data is your PyTorch tensor
print(tensor_data)

tensor([0.0000e+00, 1.9000e+01, 2.2200e+01, 2.3800e+01, 4.0200e+01, 2.4560e+02,
        1.4000e+00, 8.0000e-01, 2.8000e+00, 1.5800e+01, 6.5200e+00, 5.7600e+00,
        5.9600e+01, 8.0240e+01, 2.2000e+01, 8.3600e+01, 3.8200e+00, 4.0000e-01,
        1.8000e+00, 2.0000e+00, 1.2000e+00, 1.2000e+00, 5.4000e+00, 2.5720e+02,
        5.2000e+00, 1.3400e+01, 0.0000e+00, 2.0000e-01, 1.0000e+00, 2.3600e+01,
        2.5400e+01, 2.6600e+01, 4.0200e+01, 3.0260e+02, 2.0000e+00, 8.0000e-01,
        2.6000e+00, 1.8600e+01, 8.0800e+00, 7.2400e+00, 6.6520e+01, 9.9160e+01,
        1.9400e+01, 8.8400e+01, 4.6600e+00, 6.0000e-01, 2.0000e+00, 2.0000e+00,
        2.0000e+00, 2.2000e+00, 4.0000e+00, 1.8120e+02, 4.0000e+00, 1.1000e+01,
        4.0000e-01, 8.0000e-01])

In [ ]:
#Drop columns 0 and 29 from the concatenated data torch
selected_rows = torch.cat([tensor_data[1:28], tensor_data[29:57]])
print(selected_rows.shape)
#Make selected_rows 2d
selected_rows = selected_rows.unsqueeze(0)

torch.Size([54])

In [ ]:
net.eval()
with torch.no_grad():
    prediction_choice = net(selected_rows)
print(prediction_choice)

tensor([[44.5047, 23.1400]])